### ISSUE TITLE
Data leakage

### ISSUE THREAD

**Issue by zshoorbajee** [learn-co-curriculum/dsc-logistic-regression-in-scikit-learn#1]
## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
N/A
```

### Concern

This lab has us normalize the data **before** the train-test split. I believe we just learned in a previous lesson that this causes data leakage. Shouldn't these steps be reversed?

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by hoffm386** [comment]
Agreed, this is not following best practices. Working on a revision now!

**Comment by hoffm386** [comment]
Thanks for flagging! This was resolved in https://github.com/learn-co-curriculum/dsc-logistic-regression-in-scikit-learn/pull/2
